### ISSUE TITLE
Typo BILLING domain in AndroidManifest.xml

### ISSUE THREAD

**Issue by daisukekasahara** [sdkbox/sdkbox-iap-sample#14]
C++ js Lua
proj.andoid/AndroidManifest.xml

uses-permission android:name="android.permission.BILLING" 
↓
uses-permission android:name="com.android.vending.BILLING" 

ref:
http://developer.android.com/google/play/billing/billing_integrate.html

**Comment by yinjimmy** [comment]
thanks, fixed with https://github.com/sdkbox/sdkbox-iap-sample/commit/ef89a20cfa1f37f0de652f67fa300ebfacf87d17
