### ISSUE TITLE
Does SDKBOX IAP support verifying Receipt from AppStore

### ISSUE THREAD

**Issue by jameszhong2008** [sdkbox/sdkbox-iap-sample#2]
I want to use sdkbox to complete my In-APP purchase in iOS, does it support Verifying Receipt from Appstore or do you plan to do it in the future? 
SDKBOX is simple and nice!!
Thanks in advance

**Comment by darkdukey** [comment]
Yes we're working on receipt verification

**Comment by oostap** [comment]
Hello, I want to verify Appstore receipt via my own server. When it would be possible in sdkbox?

**Comment by xdxttt** [comment]
@yinjimmy   Do you have any plan for support verify with server side ？(App Store  and Google Play )
publish a roadmap with time schedule is very helpful.

**Comment by darkdukey** [comment]
SDKBOX 1.5.3 supports IAP receipts now, will update this sample today
